### ISSUE TITLE
如何添加监控产品

### ISSUE THREAD

**Issue by chanknight** [qqxx6661/Price-monitor#10]
数据库没怎么看懂参数意义。
想要添加一个产品是往哪个表添加，哪些字段是必须的。

**Comment by qqxx6661** [comment]
我这几天重新整理了项目，可以看一下。

**Comment by Jackey1999** [comment]
好的，谢谢


Jackey's iPhone

------------------ 原始邮件 ------------------
发件人: Zhendong Yang <notifications@github.com>
发送时间: 2019年6月18日 12:39
收件人: qqxx6661/Price-monitor <Price-monitor@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[qqxx6661/Price-monitor] 如何添加监控产品 (#10)




我这几天重新整理了项目，可以看一下。
