### ISSUE TITLE
网站出现错误了  redis是不是挂了啊？

### ISSUE THREAD

**Issue by eamonzzz** [qqxx6661/Price-monitor#13]
![image](https://user-images.githubusercontent.com/20869326/71947663-8faf9f00-3208-11ea-90e8-f6c888cc1ade.png)

**Comment by qqxx6661** [comment]
你好，昨天在切换服务器，新服务器没有部署好Redis，我先修复下，谢谢提醒。

**Comment by qqxx6661** [comment]
已经恢复，谢谢~
