### ISSUE TITLE
网站注册错误

### ISSUE THREAD

**Issue by LiyongLuo** [qqxx6661/Price-monitor#5]
您好，这个网站是暂时还未开放注册么？

**Comment by qqxx6661** [comment]
很抱歉，最近网站遭受黑客和勒索者攻击，暂时下线，烦请等待数日。

**Comment by qqxx6661** [comment]
网站已经修复，回档至一个月以前了，以前注册过的部分用户可能需要重新注册。

**Comment by LiyongLuo** [comment]
感谢，辛苦了

在 2018年9月24日，下午7:42，Zhendong Yang <notifications@github.com<mailto:notifications@github.com>> 写道：


网站已经修复，回档至一个月以前了，以前注册过的部分用户可能需要重新注册。
