### ISSUE TITLE
监控方面的建议

### ISSUE THREAD

**Issue by dancingfire88** [qqxx6661/Price-monitor#6]
作者这个产品的不知道是否有商业化的打算，如果目标客户是专业撸货群体的话，建议监控苏宁，京东，唯品会等几个平台，就目前网页规则，感觉京东的页面是最简单的。本人平时就是搞撸货，相对需求比较清楚，也在自学并参考作者的代码做爬虫。价格方面，京东的PLUS价没有参考意义，而商品监控的话，主要是数码，黄金，奶粉这几类产品，需要自动计算券后价格，黄金的话，还要自动计算出每g成本，因为京东黄金的话，有时候会有送1g活动，这种时候可能需要爬取副标题，算入成本价。所以副标题只要作为一个字段，后台爬取计算成本使用，前台界面越简洁越好。主标题的话目前参考作者完整爬取，没想好优化方式，如何做简化规则，毕竟要考虑爬取代码在不同产品判断时的通用性。

**Comment by qqxx6661** [comment]
你好，非常感谢你的建议。我之前也考虑过商业化，不过一直没有做正式的尝试，一是因为个人精力有限，二是因为没有想到足够的盈利点，也就不敢轻易地投资做这个事情。

你的建议我都看了，关于副标题优惠卷等我也思考了很多，对他们做一些文字的分析处理确实会有一些效果，我也准备之后做一些尝试，但总的来说电商的规则越来越复杂，很难保证找到一个通用的分析方法，很可能实现完一个小算法，网页改了规则后就又得去重做，没有一个专门的团队做这个真的吃不消。

现在比较成熟的是购物党的插件，能够把优惠券信息也爬出来。

![image](https://user-images.githubusercontent.com/12525295/49728257-3562a880-fcad-11e8-99ba-1c76e04fc382.png)

还有神价屋也做得不错，就是网页有点乱。
http://www.joyj.com/real/

总的来说还是个人精力不够，很多想法也没法很快地去实现出来。

对撸货我也比较感兴趣，有空可以交流交流，微信：yangzd1102

**Comment by wzh502887976** [comment]
一起惠也做的不错，只不过现在收费了
